name: llm_play
version: '3.8'
services:
  llm_play:
    image: llm_play
    build:
      context: .
      dockerfile: llm.dockerfile
    container_name: llm_play
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./textworld_map:/app/textworld_map
      - ./llm_play.py:/app/llm_play.py
      - ./app.py:/app/app.py
    ports:
      - 8000:8000
    networks:
      - llm_play_network
  ui:
    image: ui
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: ui
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    command: npx vite --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - llm_play_network
  es:
    image: elasticsearch:8.11.1
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - llm_play_network

networks:
  llm_play_network:
    driver: bridge
